# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'met_scraper_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os
sys.path.append(os.path.abspath("/home/tyler/Documents/openanal/fin/pp/"))
import metric_scraper
import sys, os
import oi_to_csv


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(168, 132)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 0, 150, 32))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.editingFinished.connect(self.populate)


        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 150, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.employees = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.employees.setObjectName("employees")
        self.verticalLayout_3.addWidget(self.employees)
        self.sector = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.sector.setObjectName("sector")
        self.verticalLayout_3.addWidget(self.sector)
        self.industry = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.industry.setObjectName("industry")
        self.verticalLayout_3.addWidget(self.industry)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "ticker"))
        self.label_5.setText(_translate("Form", "Employees"))
        self.label_6.setText(_translate("Form", "Sector"))
        self.label_4.setText(_translate("Form", "industry"))
        self.employees.setText(_translate("Form", "n/a"))
        self.sector.setText(_translate("Form", "n/a"))
        self.industry.setText(_translate("Form", "n/a"))

    def populate(self):
        self.employees.setText(metric_scraper.employees(self.lineEdit.text()))
        self.sector.setText(metric_scraper.sector(self.lineEdit.text()))
        self.industry.setText(metric_scraper.industry(self.lineEdit.text()))        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
