# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'met01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.met_scraperTBL = QtWidgets.QGroupBox(self.centralwidget)
        self.met_scraperTBL.setGeometry(QtCore.QRect(0, 0, 261, 261))
        self.met_scraperTBL.setObjectName("met_scraperTBL")
        self.tableView = QtWidgets.QTableView(self.met_scraperTBL)
        self.tableView.setGeometry(QtCore.QRect(0, 60, 256, 192))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.met_scraperTBL)
        self.label.setGeometry(QtCore.QRect(30, 80, 58, 18))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.met_scraperTBL)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 113, 32))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.met_scraperTBL.setTitle(_translate("MainWindow", "metric_scraper"))
        self.label.setText(_translate("MainWindow", "Ticker:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
